std = "roblox"
exclude = ["*.d.lua"]

[config]
# Allow for `_G.__DEV__` (etc) with packages like React-lua
global_usage = { ignore_pattern = "^__" }

[rules]
global_usage = "allow"
undefined_variable = "allow"
incorrect_standard_library_use = "allow"
if_same_then_else = "allow"
