[package]
name = "siriuslatte/interactiveworks"
description = "In-house framework used among Orion Studios games."
license = "MIT"
version = "1.3.0-alpha.1"
authors = ["Ademir Sanchez <barajasademirts@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["lib", "lib/*", "default.project.json", "wally.toml", "LICENSE"]

[dependencies]
Promise = "evaera/promise@4.0.0"
Bindables = "siriuslatte/bindables@1.0.1"
Janitor = "howmanysmall/janitor@1.17.0"